### ISSUE TITLE
Leer sobre la teoría.

### ISSUE THREAD

**Issue by Joseph-Ibanez** [Joseph-Ibanez/Proyecto-Compu#2]
No sé qué leer sobre el proyecto.

**Comment by Joseph-Ibanez** [comment]
Tenemos que leer acerca de la Störmer.

**Comment by Drillbithead** [comment]
Hay que escribir el algoritmo de Stormer-Verlet y/o el de Leap frog. Alguien ya lo hizo? 🐤
